baseURL: "chase-hunter.github.io/" 
title: Chase Hunter
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 40

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        - name: Dashboard
          url: dashboard/
          weight: 3
        - name: Courses
          url: courses/
          weight: 4
        - name: Design
          url: design/
          weight: 5        

params:
    description: "This website hosts Chase Hunter's research papers, real-time business cycle dashboard, course materials, and design templates."
    author: Chase Hunter
    googleAnalyticsID: "G-97G4MZ4061"
    images: ["cover.png"]
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    ShowWordCount: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    disableScrollToTop: true
    ShowCodeCopyButtons: true
    ShowToc: false
    TocOpen: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Chase Hunter
          subtitle: "I’m an IT Support Analyst based in the U.S., currently working at the Level 2 tier. I focus on keeping systems running smoothly, solving complex technical issues, and improving user experiences across a range of environments. My work centers on troubleshooting, infrastructure support, and making technology simpler and more reliable for the people who depend on it."
          imageUrl: "/picture.jpeg"
          imageWidth: 130
          imageHeight: 130
          buttons:
            - name: Papers
              url: papers/
            - name: Dashboard
              url: dashboard/  
            - name: Courses
              url: courses/
            - name: Design
              url: design/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:chasemhunter@gmail.com
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: YouTube
          url: https://www.youtube.com
        - name: GitHub
          url: https://github.com/chase-hunter

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Chase Hunter"

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

titleCaseStyle: 'none'
enableGitInfo: true