baseURL: "chase-hunter.github.io/" 
title: Chase Hunter
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 40

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 2
        - name: Thoughts and Interests
          url: thoughts/
          weight: 3

params:
    description: "This website hosts Chase Hunter."
    author: Chase Hunter
    ## googleAnalyticsID: ""
    images: ["cover.png"]
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    ShowWordCount: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    disableScrollToTop: true
    ShowCodeCopyButtons: true
    ShowToc: false
    TocOpen: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Chase Hunter
          subtitle: "IT professional by trade, naturally hands-on. I’m motivated by problem-solving and interests that encourage exploration, learning, and improvement."
          imageUrl: "/picture.jpeg"
          imageWidth: 130
          imageHeight: 130
          buttons:
            - name: Projects
              url: projects/
           ## - name: Thoughts and Interests
           ##   url: thoughts/
           ##   weight: 3

    socialIcons:
        - name: Email
          url: mailto:chasemhunter@gmail.com
        - name: GitHub
          url: https://github.com/chase-hunter
        - name: LinkedIn
          url: https://www.linkedin.com/in/chase-hunter-b47572235/


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Chase Hunter"

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

titleCaseStyle: 'none'
enableGitInfo: true