baseURL: "chase-hunter.github.io/" 
title: Chase Hunter
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 40

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        - name: Dashboard
          url: dashboard/
          weight: 3
        - name: Courses
          url: courses/
          weight: 4
        - name: Design
          url: design/
          weight: 5        

params:
    description: "This website hosts Chase Hunter."
    author: Chase Hunter
    googleAnalyticsID: "G-97G4MZ4061"
    images: ["cover.png"]
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    ShowWordCount: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    disableScrollToTop: true
    ShowCodeCopyButtons: true
    ShowToc: false
    TocOpen: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Chase Hunter
          subtitle: "I work in IT by day — troubleshooting, building, and keeping things stable — but most of my interests live outside the office. I like fast cars, clean design, and projects that feel handmade and personal, whether that’s a custom keyboard or tracking down a perfectly spec’d GT car."
          imageUrl: "/picture.jpeg"
          imageWidth: 130
          imageHeight: 130
          buttons:
            - name: Projects
              url: projects/
            - name: Dashboard
              url: dashboard/  

    socialIcons:
        - name: CV
          url: void.pdf
        - name: Email
          url: mailto:chasemhunter@gmail.com
        - name: GitHub
          url: https://github.com/chase-hunter

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Chase Hunter"

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

titleCaseStyle: 'none'
enableGitInfo: true